version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.asciidoctor:asciidoctorj-diagram
    versions:
    - 2.1.0
    - 2.1.1
  - dependency-name: org.apache.tomcat:tomcat-catalina
    versions:
    - 10.0.0
    - 10.0.2
    - 10.0.4
  - dependency-name: com.google.inject:guice
    versions:
    - 4.2.3
    - 5.0.0
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.9.8
